item {
  id: 1
  name: 'avocado'
}

item {
  id: 2
  name: 'asparagus'
}

item {
  id: 3
  name: 'banana'
}

item {
  id: 4
  name: 'cabbage'
}

item {
  id: 5
  name: 'cantaloupe'
}

item {
  id: 6
  name: 'carrot'
}

item {
  id: 7
  name: 'cucumber'
}

item {
  id: 8
  name: 'garlic'
}

item {
  id: 9
  name: 'ginger'
}

item {
  id: 10
  name: 'kiwi'
}

item {
  id: 11
  name: 'lemon'
}

item {
  id: 12
  name: 'lime'
}

item {
  id: 13
  name: 'mango'
}

item {
  id: 14
  name: 'purple_onion'
}

item {
  id: 15
  name: 'yellow_onion'
}

item {
  id: 16
  name: 'green_pepper'
}

item {
  id: 17
  name: 'orange_pepper'
}

item {
  id: 18
  name: 'red_pepper'
}

item {
  id: 19
  name: 'yellow_pepper'
}

item {
  id: 20
  name: 'small_potato'
}

item {
  id: 21
  name: 'sweet_potato'
}

item {
  id: 22
  name: 'pineapple'
}

item {
  id: 23
  name: 'pomegranate'
}

item {
  id: 24
  name: 'papaya'
}

item {
  id: 25
  name: 'peach'
}

item {
  id: 26
  name: 'honeydew'
}

item {
  id: 27
  name: 'tomato'
}

item {
  id: 28
  name: 'zucchini'
}

item {
  id: 29
  name: 'red_apple'
}

item {
  id: 30
  name: 'white_mushroom'
}

item {
  id: 31
  name: 'orange'
}
